# Generated by Django 5.0 on 2024-05-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='no_of_items',
            field=models.IntegerField(default='#'),
        ),
    ]
