# Generated by Django 5.0 on 2024-05-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_address_no_of_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='payment_id',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
