# Generated by Django 5.0 on 2024-06-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(blank=True, default='images/default_user_image.jpg', null=True, upload_to='images/users'),
        ),
    ]
